### ISSUE TITLE
[1.18.2] Tourmaline Hammer stats (parity change)

### ISSUE THREAD

**Issue by purejosh** [kwpugh/more_gems_fabric#53]
Hey! It appears that the Tourmaline Hammer (and possibly other ones) have fallen away from the normal attack and speed stats. The Tourmaline Hammer has 1 attack damage and 4 speed, where others like the Citrine Hammer has 4 attack damage and 1.2 speed. Just a heads up. 

I just checked, and my settings in the general.json5 are stock. 

If this has been fixed, sorry! I'm still on 1.18.2.

**Comment by kwpugh** [comment]
Yep.  I see that the values got transposed.

**Comment by kwpugh** [comment]
I found a broken set of  tool tips as well.

**Comment by kwpugh** [comment]
fixed in v71, due out as soon as CCF  stops acting up

**Comment by purejosh** [comment]
You're awesome!
