### ISSUE TITLE
Configurable values for armors

### ISSUE THREAD

**Issue by Austin001316** [kwpugh/more_gems_fabric#54]
Would be great to be able to configure the actual armor values. As far as I could see in the config there isnt anything like this, just toughness, durability and enchantability

**Comment by kwpugh** [comment]
Do you mean the head, body, leggings, and feet protection values?

**Comment by Austin001316** [comment]
Yes

**Comment by kwpugh** [comment]
ah, ok.  I had done that for other mods but was a little lazy with MoreGems because it was 40 lines to the config, plus the in code updates.   I'll add it to the list, since it does make good sense.

**Comment by Austin001316** [comment]
Much appreciated

**Comment by kwpugh** [comment]
Fortunately I'm currently making update to MoreGems 1.19.2.   I don't back port to 1.18.2 so you know.

**Comment by Austin001316** [comment]
That's fine, I am wanting it for 1.19.2

**Comment by kwpugh** [comment]
Like so...

![Screen Shot 2022-09-13 at 9 27 00 PM](https://user-images.githubusercontent.com/8809210/190044835-ac5dc6ab-ee19-4a12-9dff-fdfa201b1724.png)

**Comment by kwpugh** [comment]
I'll finish this up tomorrow and push an update later in the day.

**Comment by kwpugh** [comment]
Add in latest release.
