### ISSUE TITLE
Opinion

### ISSUE THREAD

**Issue by icedmacchiato14** [kwpugh/more_gems_fabric#55]
Just wanted to leave my opinion of this mod. Fun mod nice diverse armor and ores that bring some more life into caves. But honestly I think this mod has more features than it's name gives away.
I think this mod could benefit from no Paxels because of how unvanilla they are and in my opinion the armor is too powerful and unbalanced. I had this mod in my modpack but ended up removing it because of these features, if this had even togglable options id consider re-adding it.

**Comment by kwpugh** [comment]
Thank you for the input.

**Comment by kwpugh** [comment]
BTW:  armor values can be adjusted in the config.
