### ISSUE TITLE
Saphire hammer

### ISSUE THREAD

**Issue by Majorkrabbe** [kwpugh/more_gems_fabric#57]
How do you make it??

**Comment by kwpugh** [comment]
You really ought to the Roughly Enough Items (REI) mod, which has all the mod recipes.

![Screen Shot 2022-10-02 at 9 26 19 AM](https://user-images.githubusercontent.com/8809210/193459281-38fe7f78-19ea-4ebf-ad40-30bc95edda52.png)

**Comment by Majorkrabbe** [comment]
Ahhh. I will do that THX :-)
