### ISSUE TITLE
[1.19.2] server crashed with illegal states exception

### ISSUE THREAD

**Issue by ColdTearsYY** [kwpugh/more_gems_fabric#58]
https://paste.ubuntu.com/p/TF7KnQQGMM/
crash report

**Comment by kwpugh** [comment]
I'm pretty sure I understand the issue.  I believe that a situation is occurring where the same entity is trying  to be removed twice.   I refactored the logic to prevent that.

can you try this version on  your server to confirm?
[MoreGems-Fabric-1.19.2-1.4.48.jar.zip](https://github.com/kwpugh/more_gems_fabric/files/9697163/MoreGems-Fabric-1.19.2-1.4.48.jar.zip)

**Comment by kwpugh** [comment]
I believe this is fixed, closing.  Let me know if otherwise.

v1.4.48 is now out on Curseforge
