### ISSUE TITLE
1.19.4

### ISSUE THREAD

**Issue by Depleuer** [kwpugh/more_gems_fabric#64]
Frankly no matter what I do, this mod is just not working with 1.19.4 and unfortunitly since I wanna use this VERY cool mod with nvidium and that mod doesnt go below 1.19.4, i would like to ask if you awesome people might be able to patch the mod to also be working with 1.19.4. It would realy make my day, since I have more that just no idea how to do it. ^^

**Comment by kwpugh** [comment]
Please try 1.20.1 or 1.20.4.  1.19.4 is not a supported version for this mod.

If you have issues with the later version, let me know.
